import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation strings
const translations = {
  en: {
    appName: 'Musi-Love',
    tagline: 'Connect Through Music',
    signIn: 'Sign In with Google',
    signOut: 'Sign Out',
    home: 'Home',
    users: 'Users',
    myProfile: 'My Profile',
    profile: 'Profile',
    songs: 'Songs',
    addSong: 'Add Song',
    search: 'Search',
    searchYouTube: 'Search YouTube',
    searchPlaceholder: 'Search for songs...',
    playlist: 'Playlist',
    playlists: 'Playlists',
    createPlaylist: 'Create Playlist',
    selectPlaylist: 'Select Playlist',
    playlistName: 'Playlist Name',
    defaultPlaylist: 'My Favorites',
    description: 'Description',
    age: 'Age',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    lastSeen: 'Last Seen',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    loading: 'Loading...',
    noSongs: 'No songs yet',
    noUsers: 'No users found',
    noResults: 'No results found',
    editProfile: 'Edit Profile',
    completeProfile: 'Complete Your Profile',
    required: 'Required',
    optional: 'Optional',
    viewProfile: 'View Profile',
    playAll: 'Play All',
    nowPlaying: 'Now Playing',
    next: 'Next',
    previous: 'Previous',
    allSongs: 'All Songs',
    filterByPlaylist: 'Filter by Playlist',
    addedOn: 'Added on',
    year: 'year',
    years: 'years',
    old: 'old',
    online: 'Online',
    offline: 'Offline',
    welcome: 'Welcome to Musi-Love',
    welcomeMessage: 'Share your favorite music with the world',
    getStarted: 'Get Started',
    language: 'Language',
    selectLanguage: 'Select Language',
    members: 'Members',
    member: 'Member'
  },
  es: {
    appName: 'Musi-Love',
    tagline: 'Conecta a Través de la Música',
    signIn: 'Iniciar Sesión con Google',
    signOut: 'Cerrar Sesión',
    home: 'Inicio',
    users: 'Usuarios',
    myProfile: 'Mi Perfil',
    profile: 'Perfil',
    songs: 'Canciones',
    addSong: 'Agregar Canción',
    search: 'Buscar',
    searchYouTube: 'Buscar en YouTube',
    searchPlaceholder: 'Buscar canciones...',
    playlist: 'Lista de Reproducción',
    playlists: 'Listas de Reproducción',
    createPlaylist: 'Crear Lista',
    selectPlaylist: 'Seleccionar Lista',
    playlistName: 'Nombre de la Lista',
    defaultPlaylist: 'Mis Favoritos',
    description: 'Descripción',
    age: 'Edad',
    gender: 'Género',
    male: 'Masculino',
    female: 'Femenino',
    lastSeen: 'Última Vez Visto',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    loading: 'Cargando...',
    noSongs: 'No hay canciones aún',
    noUsers: 'No se encontraron usuarios',
    noResults: 'No se encontraron resultados',
    editProfile: 'Editar Perfil',
    completeProfile: 'Completa Tu Perfil',
    required: 'Requerido',
    optional: 'Opcional',
    viewProfile: 'Ver Perfil',
    playAll: 'Reproducir Todo',
    nowPlaying: 'Reproduciendo Ahora',
    next: 'Siguiente',
    previous: 'Anterior',
    allSongs: 'Todas las Canciones',
    filterByPlaylist: 'Filtrar por Lista',
    addedOn: 'Agregado el',
    year: 'año',
    years: 'años',
    old: 'de edad',
    online: 'En Línea',
    offline: 'Desconectado',
    welcome: 'Bienvenido a Musi-Love',
    welcomeMessage: 'Comparte tu música favorita con el mundo',
    getStarted: 'Comenzar',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    members: 'Miembros',
    member: 'Miembro'
  },
  fr: {
    appName: 'Musi-Love',
    tagline: 'Connectez-vous Par la Musique',
    signIn: 'Se Connecter avec Google',
    signOut: 'Se Déconnecter',
    home: 'Accueil',
    users: 'Utilisateurs',
    myProfile: 'Mon Profil',
    profile: 'Profil',
    songs: 'Chansons',
    addSong: 'Ajouter une Chanson',
    search: 'Rechercher',
    searchYouTube: 'Rechercher sur YouTube',
    searchPlaceholder: 'Rechercher des chansons...',
    playlist: 'Liste de Lecture',
    playlists: 'Listes de Lecture',
    createPlaylist: 'Créer une Liste',
    selectPlaylist: 'Sélectionner une Liste',
    playlistName: 'Nom de la Liste',
    defaultPlaylist: 'Mes Favoris',
    description: 'Description',
    age: 'Âge',
    gender: 'Genre',
    male: 'Masculin',
    female: 'Féminin',
    lastSeen: 'Dernière Visite',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    loading: 'Chargement...',
    noSongs: 'Pas encore de chansons',
    noUsers: 'Aucun utilisateur trouvé',
    noResults: 'Aucun résultat trouvé',
    editProfile: 'Modifier le Profil',
    completeProfile: 'Complétez Votre Profil',
    required: 'Requis',
    optional: 'Optionnel',
    viewProfile: 'Voir le Profil',
    playAll: 'Tout Jouer',
    nowPlaying: 'En Cours de Lecture',
    next: 'Suivant',
    previous: 'Précédent',
    allSongs: 'Toutes les Chansons',
    filterByPlaylist: 'Filtrer par Liste',
    addedOn: 'Ajouté le',
    year: 'an',
    years: 'ans',
    old: "d'âge",
    online: 'En Ligne',
    offline: 'Hors Ligne',
    welcome: 'Bienvenue sur Musi-Love',
    welcomeMessage: 'Partagez votre musique préférée avec le monde',
    getStarted: 'Commencer',
    language: 'Langue',
    selectLanguage: 'Sélectionner la Langue',
    members: 'Membres',
    member: 'Membre'
  },
  pt: {
    appName: 'Musi-Love',
    tagline: 'Conecte-se Através da Música',
    signIn: 'Entrar com Google',
    signOut: 'Sair',
    home: 'Início',
    users: 'Usuários',
    myProfile: 'Meu Perfil',
    profile: 'Perfil',
    songs: 'Músicas',
    addSong: 'Adicionar Música',
    search: 'Pesquisar',
    searchYouTube: 'Pesquisar no YouTube',
    searchPlaceholder: 'Pesquisar músicas...',
    playlist: 'Playlist',
    playlists: 'Playlists',
    createPlaylist: 'Criar Playlist',
    selectPlaylist: 'Selecionar Playlist',
    playlistName: 'Nome da Playlist',
    defaultPlaylist: 'Meus Favoritos',
    description: 'Descrição',
    age: 'Idade',
    gender: 'Gênero',
    male: 'Masculino',
    female: 'Feminino',
    lastSeen: 'Última Vez Visto',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    add: 'Adicionar',
    loading: 'Carregando...',
    noSongs: 'Ainda não há músicas',
    noUsers: 'Nenhum usuário encontrado',
    noResults: 'Nenhum resultado encontrado',
    editProfile: 'Editar Perfil',
    completeProfile: 'Complete Seu Perfil',
    required: 'Obrigatório',
    optional: 'Opcional',
    viewProfile: 'Ver Perfil',
    playAll: 'Tocar Todas',
    nowPlaying: 'Tocando Agora',
    next: 'Próxima',
    previous: 'Anterior',
    allSongs: 'Todas as Músicas',
    filterByPlaylist: 'Filtrar por Playlist',
    addedOn: 'Adicionado em',
    year: 'ano',
    years: 'anos',
    old: 'de idade',
    online: 'Online',
    offline: 'Offline',
    welcome: 'Bem-vindo ao Musi-Love',
    welcomeMessage: 'Compartilhe sua música favorita com o mundo',
    getStarted: 'Começar',
    language: 'Idioma',
    selectLanguage: 'Selecionar Idioma',
    members: 'Membros',
    member: 'Membro'
  }
};

const STORAGE_KEY = 'musi-love-language';

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get language from localStorage or default to English
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  };

  const t = (key) => {
    return translations[language][key] || translations.en[key] || key;
  };

  const value = {
    language,
    changeLanguage,
    t,
    availableLanguages: [
      { code: 'en', name: 'English' },
      { code: 'es', name: 'Español' },
      { code: 'fr', name: 'Français' },
      { code: 'pt', name: 'Português' }
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
